version: "3.8"

services:
  ros2-gui:
    build: .
    image: ros2-gui:humble-opencv-realsense
    container_name: ros2-gui
    runtime: nvidia
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - LIBGL_ALWAYS_INDIRECT=1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,video,graphics
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - $HOME/.Xauthority:/root/.Xauthority:rw
      - ./ros2_ws:/ros2_ws
      - /dev:/dev
    network_mode: host
    shm_size: 2g
    stdin_open: true
    tty: true
